version: "3.8"

services:
  searxng:
    image: searxng/searxng
    container_name: searxng
    ports:
      - "8081:8080"
    environment:
      - SEARXNG_BASE_URL=http://localhost:8081
    volumes:
      - ./searxng:/etc/searxng
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3000:8080"
    volumes:
      - ./webui:/app/backend/open_webui/configs/tools
    environment:
      - OLLAMA_API_BASE_URL=http://host.docker.internal:11434
    restart: unless-stopped
